---
- hosts: app
  vars:
    todoapp_user: todoapp
  tasks:
    - name: Provision the Nodejs repository
      get_url: 
        url: https://rpm.nodesource.com/setup_14.x
        dest: /tmp/nodejs_repo_setup
      register: nodejs_repo_script
    - name: Setup Nodejs repo
      when: nodejs_repo_script.changed
      become: yes
      shell: bash /tmp/nodejs_repo_setup
    - name: Make sure Nodejs is instanlled
      become: yes
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git  
        - nodejs 
    - name: Make sure the todoapp user exists
      become: yes
      user: 
        name: "{{ todoapp_user }}"
    - name: Adjust permissions in toso app folder
      become: yes
      file:
        path: /home/{{todoapp_user}}
        mode: "0755"  
    - name: Make sure the git repo  is up to  date
      become: yes
      become_user: "{{ todoapp_user }}"
      git:
        repo: https://github.com/timoguic/ACIT4640-todo-app.git
        dest: /home/{{ todoapp_user }}/app
    - name: Template out the service file
      become: yes
      template:
        src: todoapp.j2
        dest: /etc/systemd/system/todoapp.service 
    - name: Make sure NPM install is Run
      become: yes
      become_user: "{{ todoapp_user }}"
      shell: npm install
      args:
        chdir: /home/{{ todoapp_user }}/app 
    - name: Make sure the DB setting
      become: yes
      become_user: "{{todoapp_user}}"
      replace: 
        path: /home/{{todoapp_user}}/app/config/database.js
        regexp: "localhost/CHANGEME"
        replace: "192.168.150.30/ACIT4640"          
    - name: Make sure todo service is enableed and started    
      become: yes
      systemd:
        name: todoapp
        state: started
        enabled: yes    
    - name: Make sure Nodejs port is open
      become: yes
      firewalld:
        port: 8080/tcp
        state: enabled
        permanent: yes
        immediate: yes    
